# Generated by Django 4.0 on 2022-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_emailupdate'),
        ('posts', '0005_remove_post_reported_post_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(blank=True, default=None, to='users.Profile'),
        ),
    ]
