services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static:/socialmedia/static
      - media:/socialmedia/media
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - static:/socialmedia/static
      - media:/socialmedia/media
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static:
  media:
  postgres-data: