# Generated by Django 4.0 on 2022-07-25 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailupdate',
            field=models.ManyToManyField(blank=True, default=None, related_name='notifs', to=settings.AUTH_USER_MODEL),
        ),
    ]
